# eddiebot_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation:  0.448      # ← distancia entre ruedas
    wheel_radius:      0.0765       # ← radio de la rueda

    publish_rate: 50
    base_frame_id: base_footprint

    cmd_vel:
      topic: /cmd_vel
      timeout: 0.5

    enable_odom_tf: true
